Install JAVA as root
B-UMMI/docker-images pull request #6
Opened 2017-06-06 14:21 UTC by miguelpmachado

2017-06-06 14:22 UTC, tiagofilipe12 approved these changes

2017-06-07 10:13 UTC, miguelpmachado commented
@tiagofilipe12, can I merge?

2017-06-07 11:21 UTC, tiagofilipe12 requested changes

2017-06-07 11:21 UTC, tiagofilipe12 commented on snippy_tseemann/Dockerfile
> -RUN apt-get install -y build-essential curl file git python-setuptools ruby locales
may be you should separete this in different lines to simplify building process.

2017-06-07 11:55 UTC, miguelpmachado commented on snippy_tseemann/Dockerfile
> -RUN apt-get install -y build-essential curl file git python-setuptools ruby locales
It simplifies the user reading process, but increases docker build layers

2017-06-07 13:14 UTC, tiagofilipe12 approved these changes

2017-06-07 13:14 UTC, merged